/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pos.gui;

import com.pos.AddProduct;
import com.pos.Inventory;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Rafae Waqar Qazi
 */
public class InventoryGUI extends javax.swing.JFrame {

    /**
     * Creates new form Inventory
     */
    private ResultSet result;
    private Inventory inventory = new Inventory();
    public InventoryGUI() {
        initComponents();
        updateInventoryTable();
        updateCategoryBox();
        updateUnitBox();
        updateStockInOutTable();
        updateOverAllSaleTable();
        updateGroupSaleTable();
    }
    private void updateInventoryTable(){
        inventoryTable.setModel(DbUtils.resultSetToTableModel(inventory.getInventoryTableResult()));
    }
    private void updateCategoryBox(){
        try {
            AddProduct add = new AddProduct();
            result =add.getCategoryNameResult();
            while(result.next()){
                categoryBox.addItem(result.getString(1));
                filterBox.addItem(result.getString(1));
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
       
    }
    private void updateUnitBox(){
        try {
            AddProduct add = new AddProduct();
            result = add.getUnitNameResult();
            while(result.next()){
                unitBox.addItem(result.getString(1));
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    private void clearTextBoxes(){
        articleField.setText("");
        quantityField.setText("");
        buyingPriceField.setText("");
        categoryBox.setSelectedItem("");
        unitBox.setSelectedItem("");
        sellingPriceField.setText("");
        descriptionField.setText("");
        dateRegisteredField.setText("");
        dateUpdatedField.setText("");
        quantityAddField.setText("");
    }
    private void updateStockInOutTable(){
        stockInOutTable.setModel(DbUtils.resultSetToTableModel(inventory.getStockInOutTableResult()));
    }
    private void updateOverAllSaleTable(){
        overAllSaleTable.setModel(DbUtils.resultSetToTableModel(inventory.getOverAllSaleTableResult()));
    }
    private void updateGroupSaleTable(){
        groupSaleTable.setModel(DbUtils.resultSetToTableModel(inventory.getGroupSaleTableResult()));
    }
    private void setEditableTrue(){
        buyingPriceField.setEditable(true);
        sellingPriceField.setEditable(true);
        descriptionField.setEditable(true);
        quantityAddField.setEditable(true);
    }
    private void setEditableFalse(){
        articleField.setEditable(false);
        buyingPriceField.setEditable(false);
        sellingPriceField.setEditable(false);
        descriptionField.setEditable(false);
        quantityAddField.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InventoryMainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchTypeBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        filterBox = new javax.swing.JComboBox<>();
        addProductButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        quantityAddField = new javax.swing.JTextField();
        articleField = new javax.swing.JTextField();
        buyingPriceField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sellingPriceField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        descriptionField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dateRegisteredField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dateUpdatedField = new javax.swing.JTextField();
        categoryBox = new javax.swing.JComboBox<>();
        unitBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        stockSearchField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        stockInOutDetailsTable = new javax.swing.JTable();
        stockSearchTypeBox = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        stockInOutTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        overAllSaleTable = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        saleSearchField = new javax.swing.JTextField();
        saleSearchTypeBox = new javax.swing.JComboBox<>();
        saleDeleteButton = new javax.swing.JButton();
        saleClearButton = new javax.swing.JButton();
        overAllSaleGraph = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        expenseField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        profitField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        actualReturnField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lossField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        expectedReturnField = new javax.swing.JTextField();
        calculateProfitLossButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        groupSaleTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        groupSaleDetailsTable = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        groupFilterBox = new javax.swing.JComboBox<>();
        graphButton = new javax.swing.JButton();
        Inventory_Background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addCategoryUnitMenuItem = new javax.swing.JMenuItem();
        addProductMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventory");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        InventoryMainPanel.setPreferredSize(new java.awt.Dimension(900, 551));
        InventoryMainPanel.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setOpaque(false);

        jTabbedPane1.setForeground(new java.awt.Color(62, 62, 62));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(62, 62, 62));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Search_20px.png"))); // NOI18N
        jLabel1.setText("Search:");

        searchField.setColumns(12);
        searchField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchField.setForeground(new java.awt.Color(62, 62, 62));
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        searchTypeBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchTypeBox.setForeground(new java.awt.Color(62, 62, 62));
        searchTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product ID", "Article" }));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 62, 62));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Filter_16px.png"))); // NOI18N
        jLabel2.setText("Filter:");

        filterBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        filterBox.setForeground(new java.awt.Color(62, 62, 62));
        filterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        filterBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterBoxItemStateChanged(evt);
            }
        });

        addProductButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addProductButton.setForeground(new java.awt.Color(62, 62, 62));
        addProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Add_16px.png"))); // NOI18N
        addProductButton.setText("Add");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        editButton.setForeground(new java.awt.Color(62, 62, 62));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Edit_16px.png"))); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(62, 62, 62));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Delete_16px.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(62, 62, 62));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Save_16px.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jPanel5.setOpaque(false);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inventoryTable.setForeground(new java.awt.Color(62, 62, 62));
        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Article", "Category", "Desc", "Quantity", "Unit", "buyingPrice", "SellingPrice"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inventoryTable.setFocusTraversalPolicyProvider(true);
        inventoryTable.setOpaque(false);
        inventoryTable.setShowHorizontalLines(false);
        inventoryTable.setShowVerticalLines(false);
        inventoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inventoryTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(62, 62, 62));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Indefinite Article_20px.png"))); // NOI18N
        jLabel3.setText("Article");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(62, 62, 62));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Numbers Input Form_20px.png"))); // NOI18N
        jLabel4.setText("Quantity:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(62, 62, 62));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Money_20px.png"))); // NOI18N
        jLabel5.setText("Buying Price:");

        quantityField.setEditable(false);
        quantityField.setForeground(new java.awt.Color(62, 62, 62));

        quantityAddField.setEditable(false);
        quantityAddField.setForeground(new java.awt.Color(62, 62, 62));

        articleField.setEditable(false);
        articleField.setForeground(new java.awt.Color(62, 62, 62));

        buyingPriceField.setEditable(false);
        buyingPriceField.setForeground(new java.awt.Color(62, 62, 62));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(62, 62, 62));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Category_20px.png"))); // NOI18N
        jLabel6.setText("Category:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(62, 62, 62));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Unit_20px.png"))); // NOI18N
        jLabel7.setText("Unit:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(62, 62, 62));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Money_20px.png"))); // NOI18N
        jLabel8.setText("Selling Price:");

        sellingPriceField.setEditable(false);
        sellingPriceField.setForeground(new java.awt.Color(62, 62, 62));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(62, 62, 62));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Create_20px.png"))); // NOI18N
        jLabel9.setText("Description:");

        descriptionField.setEditable(false);
        descriptionField.setForeground(new java.awt.Color(62, 62, 62));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(62, 62, 62));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Google Calendar_20px.png"))); // NOI18N
        jLabel10.setText("Date Registered:");

        dateRegisteredField.setEditable(false);
        dateRegisteredField.setForeground(new java.awt.Color(62, 62, 62));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(62, 62, 62));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Google Calendar_20px.png"))); // NOI18N
        jLabel11.setText("Date Updated:");

        dateUpdatedField.setEditable(false);
        dateUpdatedField.setForeground(new java.awt.Color(62, 62, 62));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Plus Math_20px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(articleField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityAddField))
                            .addComponent(buyingPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sellingPriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(unitBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoryBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(descriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addComponent(dateRegisteredField))
                    .addComponent(dateUpdatedField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(categoryBox, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unitBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(quantityAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(articleField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(dateRegisteredField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buyingPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sellingPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(dateUpdatedField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filterBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(searchTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Products", jPanel3);

        jPanel4.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(62, 62, 62));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Search_20px.png"))); // NOI18N
        jLabel13.setText("Search");

        stockSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stockSearchFieldKeyReleased(evt);
            }
        });

        stockInOutDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        stockInOutDetailsTable.setOpaque(false);
        stockInOutDetailsTable.setShowHorizontalLines(false);
        stockInOutDetailsTable.setShowVerticalLines(false);
        jScrollPane2.setViewportView(stockInOutDetailsTable);

        stockSearchTypeBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stockSearchTypeBox.setForeground(new java.awt.Color(62, 62, 62));
        stockSearchTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product ID", "Article" }));

        stockInOutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        stockInOutTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockInOutTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(stockInOutTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stockSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(stockSearchTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockSearchTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(stockSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stock Flow", jPanel4);

        jPanel6.setOpaque(false);

        overAllSaleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        overAllSaleTable.setOpaque(false);
        jScrollPane3.setViewportView(overAllSaleTable);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(62, 62, 62));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Search_20px.png"))); // NOI18N
        jLabel25.setText("Search:");

        saleSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                saleSearchFieldKeyReleased(evt);
            }
        });

        saleSearchTypeBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        saleSearchTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search By RN", "Search By Date" }));

        saleDeleteButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        saleDeleteButton.setForeground(new java.awt.Color(62, 62, 62));
        saleDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Delete_16px.png"))); // NOI18N
        saleDeleteButton.setText("Delete");
        saleDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleDeleteButtonActionPerformed(evt);
            }
        });

        saleClearButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        saleClearButton.setForeground(new java.awt.Color(62, 62, 62));
        saleClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Empty Trash_16px.png"))); // NOI18N
        saleClearButton.setText("Clear");
        saleClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleClearButtonActionPerformed(evt);
            }
        });

        overAllSaleGraph.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        overAllSaleGraph.setForeground(new java.awt.Color(62, 62, 62));
        overAllSaleGraph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Graph Report_28px.png"))); // NOI18N
        overAllSaleGraph.setText("Graph");
        overAllSaleGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overAllSaleGraphActionPerformed(evt);
            }
        });

        jPanel1.setOpaque(false);

        expenseField.setEditable(false);
        expenseField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        expenseField.setForeground(new java.awt.Color(62, 62, 62));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(62, 62, 62));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Money_20px.png"))); // NOI18N
        jLabel18.setText("Expected Return:");

        profitField.setEditable(false);
        profitField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        profitField.setForeground(new java.awt.Color(62, 62, 62));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(62, 62, 62));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Money_20px.png"))); // NOI18N
        jLabel19.setText("Loss:");

        actualReturnField.setEditable(false);
        actualReturnField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        actualReturnField.setForeground(new java.awt.Color(62, 62, 62));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(62, 62, 62));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Money_20px.png"))); // NOI18N
        jLabel15.setText("Total Expense:");

        lossField.setEditable(false);
        lossField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lossField.setForeground(new java.awt.Color(62, 62, 62));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(62, 62, 62));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Money_20px.png"))); // NOI18N
        jLabel17.setText("Gross Profit:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(62, 62, 62));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Money_20px.png"))); // NOI18N
        jLabel16.setText("Actual Return:");

        expectedReturnField.setEditable(false);
        expectedReturnField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        expectedReturnField.setForeground(new java.awt.Color(62, 62, 62));

        calculateProfitLossButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        calculateProfitLossButton.setForeground(new java.awt.Color(62, 62, 62));
        calculateProfitLossButton.setText("Calculate Profit/Loss");
        calculateProfitLossButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateProfitLossButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expenseField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profitField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel19)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lossField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(calculateProfitLossButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(expectedReturnField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actualReturnField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(expenseField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(expectedReturnField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(actualReturnField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profitField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(lossField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(calculateProfitLossButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(overAllSaleGraph)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saleSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saleSearchTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saleDeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saleClearButton))
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saleDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleSearchTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(overAllSaleGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("OverAll Sale", jPanel6);

        jPanel8.setOpaque(false);

        groupSaleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        groupSaleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupSaleTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(groupSaleTable);

        groupSaleDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(groupSaleDetailsTable);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(62, 62, 62));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Filter_20px.png"))); // NOI18N
        jLabel26.setText("Filter By:");

        groupFilterBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        groupFilterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Daily", "LastWeek", "Monthly" }));
        groupFilterBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                groupFilterBoxItemStateChanged(evt);
            }
        });

        graphButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        graphButton.setForeground(new java.awt.Color(62, 62, 62));
        graphButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Graph Report_28px.png"))); // NOI18N
        graphButton.setText("Graph");
        graphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(groupFilterBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                        .addComponent(graphButton)
                        .addContainerGap())
                    .addComponent(jScrollPane6)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupFilterBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(graphButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Grouped Sale", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        InventoryMainPanel.add(jPanel2);
        jPanel2.setBounds(10, 20, 880, 500);

        Inventory_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/POS_Inventory_Background.jpg"))); // NOI18N
        InventoryMainPanel.add(Inventory_Background);
        Inventory_Background.setBounds(0, 0, 900, 551);

        jMenu1.setText("Options");

        addCategoryUnitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        addCategoryUnitMenuItem.setText("Add Category/Unit");
        addCategoryUnitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryUnitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(addCategoryUnitMenuItem);

        addProductMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        addProductMenuItem.setText("Add Product");
        addProductMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(addProductMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InventoryMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InventoryMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCategoryUnitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoryUnitMenuItemActionPerformed
        SettingsGUI settingsgui = new SettingsGUI();
        settingsgui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addCategoryUnitMenuItemActionPerformed

    private void inventoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTableMouseClicked
        try {
            setEditableFalse();
            int row = inventoryTable.getSelectedRow();
            String productID = (inventoryTable.getModel().getValueAt(row,0).toString());
            result = inventory.getResultFromInventoryTable(productID);
            while(result.next()){
                articleField.setText(result.getString(2));
                quantityField.setText(result.getString(5));
                buyingPriceField.setText(result.getString(7));
                categoryBox.setSelectedItem(result.getString(3));
                unitBox.setSelectedItem(result.getString(6));
                sellingPriceField.setText(result.getString(8));
                descriptionField.setText(result.getString(4));
                dateRegisteredField.setText(result.getString(9));
                dateUpdatedField.setText(result.getString(10));
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_inventoryTableMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if (!(articleField.getText().isEmpty() ||quantityField.getText().isEmpty() || buyingPriceField.getText().isEmpty() ||
            categoryBox.getSelectedItem().toString().isEmpty() ||unitBox.getSelectedItem().toString().isEmpty() ||sellingPriceField.getText().isEmpty() ||
            descriptionField.getText().isEmpty() || dateRegisteredField.getText().isEmpty() ||dateUpdatedField.getText().isEmpty())){
            setEditableTrue();
            articleField.requestFocus();
        } 
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (!(articleField.getText().isEmpty() ||quantityField.getText().isEmpty()|| buyingPriceField.getText().isEmpty()||
            categoryBox.getSelectedItem().toString().isEmpty() ||unitBox.getSelectedItem().toString().isEmpty() ||sellingPriceField.getText().isEmpty() ||
            descriptionField.getText().isEmpty() || dateRegisteredField.getText().isEmpty() ||dateUpdatedField.getText().isEmpty())){
            try{    
                int row = inventoryTable.getSelectedRow();
                String productID = (inventoryTable.getModel().getValueAt(row,0).toString());
                String article = articleField.getText();
                String category = categoryBox.getSelectedItem().toString();
                String description = descriptionField.getText();
                int quantity =(int)Double.parseDouble(quantityField.getText()) ;
                int modQuantity =(int) Double.parseDouble(quantityAddField.getText());
                quantity+=modQuantity;
                String unit = unitBox.getSelectedItem().toString();
                int buyingPrice = (int)Double.parseDouble(buyingPriceField.getText());
                int sellingPrice =(int) Double.parseDouble(sellingPriceField.getText());
                String registeredDate = dateRegisteredField.getText();
                LocalDate dateUpdate = LocalDate.now();
                inventory.updateExistingProducts(productID,article,category,description,quantity,unit,buyingPrice,sellingPrice,registeredDate,dateUpdate);
                inventory.addStockIn(productID,article,modQuantity,dateUpdate.toString());
                updateInventoryTable();
                inventoryTable.getSelectionModel().clearSelection();
                clearTextBoxes();
                JOptionPane.showMessageDialog(null, "User's Information Updated Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Quantity, and Price should be in Integer! and cannot be NULL","Warning!",JOptionPane.WARNING_MESSAGE);
            }
            catch(ArrayIndexOutOfBoundsException e){
                System.out.println(e.getMessage());
            }
        }
        else {
                JOptionPane.showMessageDialog(null, "Cannot Save Information.. Because There isn't any :)","Access Denied!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        if (!searchField.getText().isEmpty()) {
            String search = searchField.getText();
            String type = searchTypeBox.getSelectedItem().toString();
            if (type.equals("Product ID")) {
                inventoryTable.setModel(DbUtils.resultSetToTableModel(inventory.searchByProductID(search)));
            }
            else{
                inventoryTable.setModel(DbUtils.resultSetToTableModel(inventory.searchByArticle(search)));
            }
        }
        else{
            updateInventoryTable();
        }
    }//GEN-LAST:event_searchFieldKeyReleased

    private void filterBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterBoxItemStateChanged
        String filter = filterBox.getSelectedItem().toString();
        if (filter.equals("All")) {
            updateInventoryTable();
        }
        else{
            inventoryTable.setModel(DbUtils.resultSetToTableModel(inventory.filterByCategory(filter)));
        }
    }//GEN-LAST:event_filterBoxItemStateChanged

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        AddProductGUI product = new AddProductGUI();
        product.setVisible(true);
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void addProductMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductMenuItemActionPerformed
        addProductButtonActionPerformed(evt);
    }//GEN-LAST:event_addProductMenuItemActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (!(inventoryTable.getSelectionModel().isSelectionEmpty())) {
        int row = inventoryTable.getSelectedRow();
        String productID = (inventoryTable.getModel().getValueAt(row,0).toString());
            if(inventory.deleteProduct(productID)){
                JOptionPane.showMessageDialog(null, "Product Deleted Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
                updateInventoryTable();
            }
            else{
                JOptionPane.showMessageDialog(null, "Cannot Delete Product!\nProduct is Already in use!","Error!",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void stockInOutTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockInOutTableMouseClicked
        if (!stockInOutTable.getSelectionModel().isSelectionEmpty()) {
            int row = stockInOutTable.getSelectedRow();
            String productID = (stockInOutTable.getModel().getValueAt(row,0).toString());
            stockInOutDetailsTable.setModel(DbUtils.resultSetToTableModel(inventory.getResultForStockInOutDetailsTable(productID)));
        }


    }//GEN-LAST:event_stockInOutTableMouseClicked

    private void stockSearchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockSearchFieldKeyReleased
        if (!stockSearchField.getText().isEmpty()) {
            String search = stockSearchField.getText();
            String type = stockSearchTypeBox.getSelectedItem().toString();
            if (type.equals("Product ID")) {
                stockInOutTable.setModel(DbUtils.resultSetToTableModel(inventory.searchStockByProductID(search)));
            }
            else{
                stockInOutTable.setModel(DbUtils.resultSetToTableModel(inventory.searchStockByArticle(search)));
            }
        }
        else
        {
            updateStockInOutTable();
        }
    }//GEN-LAST:event_stockSearchFieldKeyReleased

    private void saleClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleClearButtonActionPerformed
        if (inventory.emptySale()) {
            JOptionPane.showMessageDialog(null, "Cleared Successfully!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Cannot Clear All Sale","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_saleClearButtonActionPerformed

    private void saleDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleDeleteButtonActionPerformed
        if (!overAllSaleTable.getSelectionModel().isSelectionEmpty()) {
            int row = overAllSaleTable.getSelectedRow();
            String saleID = (overAllSaleTable.getModel().getValueAt(row,0).toString());
            if (inventory.deleteSale(saleID)) {
                JOptionPane.showMessageDialog(null, "Sale Deleted Successfully!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Cannot Delete Sale","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saleDeleteButtonActionPerformed

    private void saleSearchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saleSearchFieldKeyReleased
        if (!saleSearchField.getText().isEmpty()) {
            String search = saleSearchField.getText();
            String type = saleSearchTypeBox.getSelectedItem().toString();
            if (type.equals("Search By RN")) {
                overAllSaleTable.setModel(DbUtils.resultSetToTableModel(inventory.searchSaleByRN(search)));
            }
            else{
                overAllSaleTable.setModel(DbUtils.resultSetToTableModel(inventory.searchSaleByDate(search)));
            }
        }
        else
        {
            updateOverAllSaleTable();
        }
    }//GEN-LAST:event_saleSearchFieldKeyReleased

    private void groupSaleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupSaleTableMouseClicked
        try{
            String filter = groupFilterBox.getSelectedItem().toString();
        if (filter.equals("All")) {
            if (!groupSaleTable.getSelectionModel().isSelectionEmpty()) {
                int row = groupSaleTable.getSelectedRow();
                String receiptNo = (groupSaleTable.getModel().getValueAt(row,0).toString());
                groupSaleDetailsTable.setModel(DbUtils.resultSetToTableModel(inventory.getAllResultForGroupSaleDetailsTable(receiptNo)));
            }
        }
        else if (filter.equals("Daily")) {
                int row = groupSaleTable.getSelectedRow();
                String date = (groupSaleTable.getModel().getValueAt(row,0).toString());
                groupSaleDetailsTable.setModel(DbUtils.resultSetToTableModel(inventory.getDailyResultForGroupSaleDetailsTable(date)));
        }
        else if (filter.equals("LastWeek")) {
                int row = groupSaleTable.getSelectedRow();
                String year = (groupSaleTable.getModel().getValueAt(row,0).toString());
                String week = (groupSaleTable.getModel().getValueAt(row,1).toString());
                groupSaleDetailsTable.setModel(DbUtils.resultSetToTableModel(inventory.getWeeklyResultForGroupSaleDetailsTable(week,year)));
        }
        else{
                int row = groupSaleTable.getSelectedRow();
                String year = (groupSaleTable.getModel().getValueAt(row,0).toString());
                String month = (groupSaleTable.getModel().getValueAt(row,1).toString());
                groupSaleDetailsTable.setModel(DbUtils.resultSetToTableModel(inventory.getMonthlyResultForGroupSaleDetailsTable(year,month)));
        }
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Please Select Row!","Warning",JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_groupSaleTableMouseClicked

    private void groupFilterBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_groupFilterBoxItemStateChanged
        String filter = groupFilterBox.getSelectedItem().toString();
        if (filter.equals("All")) {
            updateGroupSaleTable();
        }
        else if (filter.equals("Daily")) {
            groupSaleTable.setModel(DbUtils.resultSetToTableModel(inventory.dailyUpdateSaleTable()));
        }
        else if (filter.equals("LastWeek")) {
            groupSaleTable.setModel(DbUtils.resultSetToTableModel(inventory.weeklyUpdateSaleTable()));
        }
        else{
            groupSaleTable.setModel(DbUtils.resultSetToTableModel(inventory.monthlyUpdateSaleTable()));
        }
        
    }//GEN-LAST:event_groupFilterBoxItemStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainMenuGUI menu = new MainMenuGUI();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void graphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphButtonActionPerformed
        String filter = groupFilterBox.getSelectedItem().toString();

        if (filter.equals("Daily")) {
            inventory.dailyGraph();
        }
        else if (filter.equals("LastWeek")) {
            inventory.weeklyGraph();
        }
        else if(filter.equals("Monthly")){
            inventory.monthlyGraph();
        }        
    }//GEN-LAST:event_graphButtonActionPerformed

    private void overAllSaleGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overAllSaleGraphActionPerformed
        inventory.overAllSaleGraph();
    }//GEN-LAST:event_overAllSaleGraphActionPerformed

    private void calculateProfitLossButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateProfitLossButtonActionPerformed
        try {
            long expense = 0,totalReturn = 0,expectedReturn = 0;
            result = inventory.calculateProfit();
            while(result.next()){
                expense =Long.parseLong(result.getString(1));
                expectedReturn = Long.parseLong(result.getString(2));
                totalReturn = Long.parseLong(result.getString(3));
            }
            expenseField.setText(String.valueOf(expense));
            actualReturnField.setText(String.valueOf(totalReturn));
            expectedReturnField.setText(String.valueOf(expectedReturn));
            if (expense<totalReturn) {
                profitField.setText(String.valueOf(totalReturn-expense));
                lossField.setText("0");
            }
            else{
                profitField.setText("0");
                lossField.setText(String.valueOf(expense-totalReturn));
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_calculateProfitLossButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InventoryMainPanel;
    private javax.swing.JLabel Inventory_Background;
    private javax.swing.JTextField actualReturnField;
    private javax.swing.JMenuItem addCategoryUnitMenuItem;
    private javax.swing.JButton addProductButton;
    private javax.swing.JMenuItem addProductMenuItem;
    private javax.swing.JTextField articleField;
    private javax.swing.JTextField buyingPriceField;
    private javax.swing.JButton calculateProfitLossButton;
    private javax.swing.JComboBox<String> categoryBox;
    private javax.swing.JTextField dateRegisteredField;
    private javax.swing.JTextField dateUpdatedField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JButton editButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JTextField expectedReturnField;
    private javax.swing.JTextField expenseField;
    private javax.swing.JComboBox<String> filterBox;
    private javax.swing.JButton graphButton;
    private javax.swing.JComboBox<String> groupFilterBox;
    private javax.swing.JTable groupSaleDetailsTable;
    private javax.swing.JTable groupSaleTable;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lossField;
    private javax.swing.JButton overAllSaleGraph;
    private javax.swing.JTable overAllSaleTable;
    private javax.swing.JTextField profitField;
    private javax.swing.JTextField quantityAddField;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton saleClearButton;
    private javax.swing.JButton saleDeleteButton;
    private javax.swing.JTextField saleSearchField;
    private javax.swing.JComboBox<String> saleSearchTypeBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox<String> searchTypeBox;
    private javax.swing.JTextField sellingPriceField;
    private javax.swing.JTable stockInOutDetailsTable;
    private javax.swing.JTable stockInOutTable;
    private javax.swing.JTextField stockSearchField;
    private javax.swing.JComboBox<String> stockSearchTypeBox;
    private javax.swing.JComboBox<String> unitBox;
    // End of variables declaration//GEN-END:variables
}
