/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pos.gui;
import com.pos.Login;
import javax.swing.*;
/**
 *
 * @author Rafae Waqar Qazi
 */
public class MainMenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuGUI
     */
    public MainMenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuPanel = new javax.swing.JPanel();
        posButton = new javax.swing.JButton();
        posLabel = new javax.swing.JLabel();
        inventoryButton = new javax.swing.JButton();
        inventoryLabel = new javax.swing.JLabel();
        settingsButton = new javax.swing.JButton();
        settingsLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        logoutLabel = new javax.swing.JLabel();
        mainMenuBackgound = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        newSaleMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setName("Main Menu"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(700, 400));

        mainMenuPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        mainMenuPanel.setLayout(null);

        posButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Cash Register_80px.png"))); // NOI18N
        posButton.setBorder(null);
        posButton.setContentAreaFilled(false);
        posButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                posButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                posButtonMouseExited(evt);
            }
        });
        posButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posButtonActionPerformed(evt);
            }
        });
        mainMenuPanel.add(posButton);
        posButton.setBounds(310, 160, 80, 80);

        posLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        posLabel.setForeground(new java.awt.Color(62, 62, 62));
        posLabel.setText("Point of Sale");
        mainMenuPanel.add(posLabel);
        posLabel.setBounds(310, 240, 80, 20);

        inventoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Scan Stock_80px.png"))); // NOI18N
        inventoryButton.setBorder(null);
        inventoryButton.setContentAreaFilled(false);
        inventoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryButtonMouseExited(evt);
            }
        });
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });
        mainMenuPanel.add(inventoryButton);
        inventoryButton.setBounds(410, 160, 80, 80);

        inventoryLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inventoryLabel.setForeground(new java.awt.Color(62, 62, 62));
        inventoryLabel.setText("Inventory");
        mainMenuPanel.add(inventoryLabel);
        inventoryLabel.setBounds(420, 240, 60, 20);

        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Settings_80px.png"))); // NOI18N
        settingsButton.setBorder(null);
        settingsButton.setBorderPainted(false);
        settingsButton.setContentAreaFilled(false);
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
        });
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        mainMenuPanel.add(settingsButton);
        settingsButton.setBounds(500, 160, 90, 80);

        settingsLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        settingsLabel.setForeground(new java.awt.Color(62, 62, 62));
        settingsLabel.setText("Settings");
        mainMenuPanel.add(settingsLabel);
        settingsLabel.setBounds(520, 240, 60, 20);

        logoutButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(62, 62, 62));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Logout Rounded Up_80px.png"))); // NOI18N
        logoutButton.setContentAreaFilled(false);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        mainMenuPanel.add(logoutButton);
        logoutButton.setBounds(590, 170, 80, 70);

        logoutLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(62, 62, 62));
        logoutLabel.setText("Logout");
        mainMenuPanel.add(logoutLabel);
        logoutLabel.setBounds(610, 240, 50, 20);

        mainMenuBackgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/POS_MainMenu_Background.jpg"))); // NOI18N
        mainMenuPanel.add(mainMenuBackgound);
        mainMenuBackgound.setBounds(0, 0, 700, 400);

        jMenu3.setText("File");

        newSaleMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newSaleMenuItem.setText("New Sale");
        newSaleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSaleMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(newSaleMenuItem);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Add New Product");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(exitMenuItem);

        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
     System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void posButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posButtonActionPerformed
        PosGUI posgui = new PosGUI();
        posgui.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_posButtonActionPerformed

    private void posButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posButtonMouseEntered
        posButton.setIcon(new ImageIcon(getClass().getResource("/com/pos/icons/Cash Register_80px2.png")));
    }//GEN-LAST:event_posButtonMouseEntered

    private void posButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posButtonMouseExited
        posButton.setIcon(new ImageIcon(getClass().getResource("/com/pos/icons/Cash Register_80px.png")));
    }//GEN-LAST:event_posButtonMouseExited

    private void inventoryButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryButtonMouseEntered
        inventoryButton.setIcon(new ImageIcon(getClass().getResource("/com/pos/icons/Move Stock_80px.png")));
    }//GEN-LAST:event_inventoryButtonMouseEntered

    private void inventoryButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryButtonMouseExited
         inventoryButton.setIcon(new ImageIcon(getClass().getResource("/com/pos/icons/Scan Stock_80px.png")));
    }//GEN-LAST:event_inventoryButtonMouseExited

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LoginGUI login = new LoginGUI();
        Login l = new Login();
        l.setOnlineUser("");
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseEntered
       settingsButton.setIcon(new ImageIcon(getClass().getResource("/com/pos/icons/Settings_80px1.png")));
    }//GEN-LAST:event_settingsButtonMouseEntered

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseExited
       settingsButton.setIcon(new ImageIcon(getClass().getResource("/com/pos/icons/Settings_80px.png")));
    }//GEN-LAST:event_settingsButtonMouseExited

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
       logoutButton.setIcon(new ImageIcon(getClass().getResource("/com/pos/icons/Logout Rounded Left_80px.png")));
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        logoutButton.setIcon(new ImageIcon(getClass().getResource("/com/pos/icons/Logout Rounded Up_80px.png")));
    }//GEN-LAST:event_logoutButtonMouseExited

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
       InventoryGUI ingui =new InventoryGUI();
       ingui.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        SettingsGUI settings = new SettingsGUI();
        settings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void newSaleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSaleMenuItemActionPerformed
        posButtonActionPerformed(evt);
    }//GEN-LAST:event_newSaleMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AddProductGUI product = new AddProductGUI();
        product.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JLabel inventoryLabel;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel mainMenuBackgound;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newSaleMenuItem;
    private javax.swing.JButton posButton;
    private javax.swing.JLabel posLabel;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel settingsLabel;
    // End of variables declaration//GEN-END:variables
}
