/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pos.gui;

import com.pos.AddProduct;
import com.pos.Inventory;
import com.pos.Login;
import com.pos.Pos;
import com.pos.database.MySqlConnection;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author Rafae Waqar Qazi
 */
public class PosGUI extends javax.swing.JFrame {

    /**
     * Creates new form PosGUI
     */
    private ResultSet result;
    private Pos pos = new Pos();
    Connection conn;
    //Constructor
    public PosGUI() {
        initComponents();
        updateStockTable();
        updateCartTable();
        updateCategoryBox();
        LocalDate localdate = LocalDate.now();
        dateField.setText(localdate.toString());
        updateReceiptNumber();
        conn = MySqlConnection.getConnection();
    }//end constructor
    
    private void updateStockTable(){
        try {
            stockTable.setModel(DbUtils.resultSetToTableModel(pos.getStockTableResult()));
        }
        catch(NullPointerException e){
           JOptionPane.showMessageDialog(null, "Error Occured while updating Table","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void updateCartTable(){
        try {
            cartTable.setModel(DbUtils.resultSetToTableModel(pos.getCartTableResult()));
        }
        catch(NullPointerException e){
           JOptionPane.showMessageDialog(null, "Error Occured while updating Table","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void updateCategoryBox(){
        try {
            AddProduct add = new AddProduct();
            result =add.getCategoryNameResult();
            while(result.next()){
                filterBox.addItem(result.getString(1));
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
       
    }
    private void updateReceiptNumber(){
        try {
            int RN =pos.getReceiptNumber();
            RN++;
            ReceiptNoField.setText(String.valueOf(RN));
        }
        catch(NullPointerException e){
           JOptionPane.showMessageDialog(null, "Error Occured while updating Table","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void emptyTextFields(){
        articleField.setText("");
        descriptionField.setText("");
        priceField.setText("");
        quantityHandField.setText("");
        quantityBuyField.setText("");
        cartArticleField.setText("");
        cartDiscField.setText("");
        cartQuantityField.setText("");
        discField.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        posMainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        filterBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        discField = new javax.swing.JTextField();
        addToCartButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        articleField = new javax.swing.JTextField();
        descriptionField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        quantityHandField = new javax.swing.JTextField();
        quantityBuyField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        transactionField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        paymentButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        printReceiptButton = new javax.swing.JButton();
        totalField = new javax.swing.JTextField();
        paymentField = new javax.swing.JTextField();
        changeField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ReceiptNoField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cartArticleField = new javax.swing.JTextField();
        cartDiscField = new javax.swing.JTextField();
        cartQuantityField = new javax.swing.JTextField();
        removeFromCartButton = new javax.swing.JButton();
        cancelTransactionButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        pos_Background = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Point Of Sale");
        setMinimumSize(new java.awt.Dimension(930, 611));
        setName("PosGUI"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        posMainPanel.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setOpaque(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Available Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(62, 62, 62))); // NOI18N
        jPanel3.setOpaque(false);

        stockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stockTable.setOpaque(false);
        stockTable.setShowHorizontalLines(false);
        stockTable.setShowVerticalLines(false);
        stockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stockTable);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 62, 62));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Search_16px.png"))); // NOI18N
        jLabel2.setText("Search:");

        searchField.setColumns(12);
        searchField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchField.setForeground(new java.awt.Color(62, 62, 62));
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(62, 62, 62));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Filter_16px.png"))); // NOI18N
        jLabel3.setText("Filter by Category:");

        filterBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        filterBox.setForeground(new java.awt.Color(62, 62, 62));
        filterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        filterBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(filterBox, 0, 123, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setOpaque(false);

        discField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        discField.setForeground(new java.awt.Color(62, 62, 62));

        addToCartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Shopping Cart_100px.png"))); // NOI18N
        addToCartButton.setContentAreaFilled(false);
        addToCartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addToCartButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addToCartButtonMouseExited(evt);
            }
        });
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(62, 62, 62));
        jLabel9.setText("Disc:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(62, 62, 62));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Indefinite Article_20px.png"))); // NOI18N
        jLabel4.setText("Article:");

        articleField.setEditable(false);
        articleField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        articleField.setForeground(new java.awt.Color(62, 62, 62));

        descriptionField.setEditable(false);
        descriptionField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descriptionField.setForeground(new java.awt.Color(62, 62, 62));

        priceField.setEditable(false);
        priceField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        priceField.setForeground(new java.awt.Color(62, 62, 62));

        quantityHandField.setEditable(false);
        quantityHandField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quantityHandField.setForeground(new java.awt.Color(62, 62, 62));

        quantityBuyField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quantityBuyField.setForeground(new java.awt.Color(62, 62, 62));
        quantityBuyField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantityBuyFieldFocusLost(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(62, 62, 62));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Create_20px.png"))); // NOI18N
        jLabel18.setText("Description:");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(62, 62, 62));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Money_20px.png"))); // NOI18N
        jLabel19.setText("Price");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(62, 62, 62));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Numbers Input Form_20px.png"))); // NOI18N
        jLabel20.setText("Qty-in-Hand:");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(62, 62, 62));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Numbers Input Form_20px.png"))); // NOI18N
        jLabel21.setText("Qty-to-Buy:");

        dateField.setEditable(false);
        dateField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dateField.setForeground(new java.awt.Color(62, 62, 62));

        transactionField.setEditable(false);
        transactionField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        transactionField.setForeground(new java.awt.Color(62, 62, 62));
        transactionField.setText("Cash");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(articleField, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(descriptionField)
                    .addComponent(priceField)
                    .addComponent(quantityHandField)
                    .addComponent(quantityBuyField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(discField))
                        .addComponent(addToCartButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(transactionField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(articleField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(transactionField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(discField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(quantityHandField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addToCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(62, 62, 62));
        jLabel10.setText("TOTAL:");

        paymentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Receive Cash_100px1.png"))); // NOI18N
        paymentButton.setContentAreaFilled(false);
        paymentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paymentButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paymentButtonMouseExited(evt);
            }
        });
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(62, 62, 62));
        jLabel11.setText("PAYMENT:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(62, 62, 62));
        jLabel13.setText("CHANGE:");

        printReceiptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Print_100px.png"))); // NOI18N
        printReceiptButton.setContentAreaFilled(false);
        printReceiptButton.setEnabled(false);
        printReceiptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printReceiptButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printReceiptButtonMouseExited(evt);
            }
        });
        printReceiptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReceiptButtonActionPerformed(evt);
            }
        });

        totalField.setEditable(false);
        totalField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        totalField.setForeground(new java.awt.Color(62, 62, 62));

        paymentField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        changeField.setEditable(false);
        changeField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalField)
                            .addComponent(paymentField)
                            .addComponent(changeField))))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printReceiptButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paymentField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(printReceiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        posMainPanel.add(jPanel2);
        jPanel2.setBounds(0, 0, 930, 280);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setOpaque(false);

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setForeground(new java.awt.Color(62, 62, 62));
        jPanel8.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(62, 62, 62));
        jLabel14.setText("RN #:");

        ReceiptNoField.setEditable(false);
        ReceiptNoField.setColumns(10);
        ReceiptNoField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ReceiptNoField.setForeground(new java.awt.Color(62, 62, 62));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(62, 62, 62));
        jLabel15.setText("Article:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(62, 62, 62));
        jLabel16.setText("Disc:");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(62, 62, 62));
        jLabel17.setText("Quantity:");

        cartArticleField.setEditable(false);
        cartArticleField.setColumns(14);
        cartArticleField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cartArticleField.setForeground(new java.awt.Color(62, 62, 62));

        cartDiscField.setEditable(false);
        cartDiscField.setColumns(10);
        cartDiscField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cartDiscField.setForeground(new java.awt.Color(62, 62, 62));

        cartQuantityField.setEditable(false);
        cartQuantityField.setColumns(10);
        cartQuantityField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cartQuantityField.setForeground(new java.awt.Color(62, 62, 62));

        removeFromCartButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        removeFromCartButton.setForeground(new java.awt.Color(62, 62, 62));
        removeFromCartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Clear Shopping Cart_32px.png"))); // NOI18N
        removeFromCartButton.setText("Remove From Cart");
        removeFromCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromCartButtonActionPerformed(evt);
            }
        });

        cancelTransactionButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelTransactionButton.setForeground(new java.awt.Color(62, 62, 62));
        cancelTransactionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Transaction_32px.png"))); // NOI18N
        cancelTransactionButton.setText("Cancel Transaction");
        cancelTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTransactionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReceiptNoField)
                            .addComponent(cartQuantityField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cartArticleField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cartDiscField)))
                    .addComponent(removeFromCartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelTransactionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ReceiptNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cartArticleField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel16)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cartDiscField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cartQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeFromCartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelTransactionButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Products in Cart", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(62, 62, 62))); // NOI18N
        jPanel7.setOpaque(false);

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartTable.setOpaque(false);
        cartTable.setShowHorizontalLines(false);
        cartTable.setShowVerticalLines(false);
        cartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cartTable);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        posMainPanel.add(jPanel6);
        jPanel6.setBounds(0, 280, 930, 310);

        pos_Background.setIcon(new javax.swing.ImageIcon("E:\\Logo\\POS_Background.jpg")); // NOI18N
        posMainPanel.add(pos_Background);
        pos_Background.setBounds(0, 0, 930, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(posMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(posMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartButtonMouseEntered
        addToCartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Add Shopping Cart_100px.png")));
    }//GEN-LAST:event_addToCartButtonMouseEntered

    private void addToCartButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartButtonMouseExited
        addToCartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Shopping Cart_100px.png")));
    }//GEN-LAST:event_addToCartButtonMouseExited

    private void paymentButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentButtonMouseEntered
        paymentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Receive Cash_100px2.png")));
    }//GEN-LAST:event_paymentButtonMouseEntered

    private void paymentButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentButtonMouseExited
        paymentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Receive Cash_100px1.png")));
    }//GEN-LAST:event_paymentButtonMouseExited

    private void printReceiptButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printReceiptButtonMouseEntered
        printReceiptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Print_100px1.png")));
    }//GEN-LAST:event_printReceiptButtonMouseEntered

    private void printReceiptButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printReceiptButtonMouseExited
        printReceiptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pos/icons/Print_100px.png")));
    }//GEN-LAST:event_printReceiptButtonMouseExited

    private void stockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockTableMouseClicked
        try {
            int row = stockTable.getSelectedRow();
            String productID = (stockTable.getModel().getValueAt(row,0).toString());
            result = pos.getResultFromStockTable(productID);
            while(result.next()){
                articleField.setText(result.getString(1));
                descriptionField.setText(result.getString(2));
                priceField.setText(result.getString(3));
                quantityHandField.setText(result.getString(4)); 
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_stockTableMouseClicked

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        String search = searchField.getText();
        if (!search.isEmpty()) {
            stockTable.setModel(DbUtils.resultSetToTableModel(pos.search(search)));
        }
        else
        {
            updateStockTable();
        }
    }//GEN-LAST:event_searchFieldKeyReleased

    private void filterBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterBoxItemStateChanged
        String filter = filterBox.getSelectedItem().toString();
        if (filter.equals("All")) {
            updateStockTable();
        }
        else{
            stockTable.setModel(DbUtils.resultSetToTableModel(pos.filterByCategory(filter)));
        }
    }//GEN-LAST:event_filterBoxItemStateChanged

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        try{
            if (!stockTable.getSelectionModel().isSelectionEmpty()) {
                int RN = (int) Double.parseDouble(ReceiptNoField.getText());
                int row = stockTable.getSelectedRow();
                String productID = (stockTable.getModel().getValueAt(row,0).toString());
                String article = articleField.getText();
                String description = descriptionField.getText();
                int productQuantity = (int) Double.parseDouble(quantityHandField.getText());
                int quantityToBuy =(int)Double.parseDouble(quantityBuyField.getText());
                int price = (int)Double.parseDouble(priceField.getText());
                int total;
                int disc = (int)Double.parseDouble(discField.getText());
                if (discField.getText().isEmpty()) {
                    total=quantityToBuy*price;
                }
                else{
                    total=quantityToBuy*price;
                    total-=((total/100)*disc);
                }   
                String date = dateField.getText();
                String transaction = transactionField.getText();
                if (pos.addToCart(RN,productID,article,description,price,quantityToBuy,disc,total,date,transaction)) {
                    updateCartTable();
                    productQuantity-=quantityToBuy;
                    pos.updateProductQuantity(productID,productQuantity);
                    JOptionPane.showMessageDialog(null, "Product Added Successfully!");
                    total=pos.calculateTotal();
                    totalField.setText(String.valueOf(total));
                    emptyTextFields();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Product is Already Entered!\nPlease Remove it First in order to Enter New","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"All Fields Need to be filled!","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Quantity and Disc should be an Integer Value! and cannot be NULL","Warning!",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void cancelTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTransactionButtonActionPerformed
        pos.emptyCart();
        updateCartTable();
    }//GEN-LAST:event_cancelTransactionButtonActionPerformed

    private void removeFromCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromCartButtonActionPerformed
        try{
            Inventory inventory = new Inventory();
            int row = cartTable.getSelectedRow();
            String productID = (cartTable.getModel().getValueAt(row,1).toString());
            int quantity = (int) Double.parseDouble(cartQuantityField.getText());
            int productQuantity = inventory.getProductQuantity(productID);
            productQuantity+=quantity;
            pos.updateProductQuantity(productID,productQuantity);
            pos.removeFromCart(productID);
            updateCartTable();
            int total=pos.calculateTotal();
            totalField.setText(String.valueOf(total));
            emptyTextFields();
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please Select Item","Warning!",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_removeFromCartButtonActionPerformed

    private void quantityBuyFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantityBuyFieldFocusLost
       try {
           int productQuantity = (int)Double.parseDouble(quantityHandField.getText());
           int quantityToBuy = (int)Double.parseDouble(quantityBuyField.getText());
           if (quantityToBuy > productQuantity && quantityToBuy > 0) {
               JOptionPane.showMessageDialog(null,"Quantity Should be less/equal to In Hand Quantity!\nand cannot be a negative Value","Warning!",JOptionPane.WARNING_MESSAGE);
               quantityBuyField.setText("");
           }
       }
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null,"Quantity In Hand Should be an Integer Value! and cannot be NULL","Warning!",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_quantityBuyFieldFocusLost

    private void cartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartTableMouseClicked
        int row = cartTable.getSelectedRow();
        cartArticleField.setText(cartTable.getModel().getValueAt(row,2).toString());
        cartDiscField.setText(cartTable.getModel().getValueAt(row,6).toString());
        cartQuantityField.setText(cartTable.getModel().getValueAt(row,5).toString());
    }//GEN-LAST:event_cartTableMouseClicked

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        try{
        int total = (int)Double.parseDouble(totalField.getText());
        int paid = (int)Double.parseDouble(paymentField.getText());
        if (paid >= total) {
            int change = paid-total;
            changeField.setText(String.valueOf(change));
            pos.makeSale();
            Inventory inventory = new Inventory();
            inventory.addStockOut();
            printReceiptButton.setEnabled(true);
            pos.updateReceipt(ReceiptNoField.getText(),dateField.getText(),total);
            updateReceiptNumber();
        }
        else{
            JOptionPane.showMessageDialog(null,"Amount is not Enough!","Error!",JOptionPane.ERROR_MESSAGE);
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Please Enter Amount","Error!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void printReceiptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReceiptButtonActionPerformed
        pos.printReceipt();
        printReceiptButton.setEnabled(false);
        pos.emptyCart();
    }//GEN-LAST:event_printReceiptButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try{
            Login l = new Login();
        
            if (l.getUserType().equals("Employee")) {
                System.exit(0);
            }
            else{
                MainMenuGUI menu = new MainMenuGUI();
                menu.setVisible(true);
                this.dispose();
            }
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "User is not Logged-in!","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ReceiptNoField;
    private javax.swing.JButton addToCartButton;
    private javax.swing.JTextField articleField;
    private javax.swing.JButton cancelTransactionButton;
    private javax.swing.JTextField cartArticleField;
    private javax.swing.JTextField cartDiscField;
    private javax.swing.JTextField cartQuantityField;
    private javax.swing.JTable cartTable;
    private javax.swing.JTextField changeField;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JTextField discField;
    private javax.swing.JComboBox<String> filterBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton paymentButton;
    private javax.swing.JTextField paymentField;
    private javax.swing.JPanel posMainPanel;
    private javax.swing.JLabel pos_Background;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton printReceiptButton;
    private javax.swing.JTextField quantityBuyField;
    private javax.swing.JTextField quantityHandField;
    private javax.swing.JButton removeFromCartButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable stockTable;
    private javax.swing.JTextField totalField;
    private javax.swing.JTextField transactionField;
    // End of variables declaration//GEN-END:variables
}
